# Generated by Django 5.0.6 on 2024-06-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_invoice_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemline',
            options={'verbose_name_plural': 'ItemLines'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
