# Generated by Django 5.0.6 on 2024-06-15 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_itemline_options_alter_invoice_invoice_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-date']},
        ),
    ]
